### ISSUE TITLE
sbatch-star-check.sh failing

### ISSUE THREAD

**Issue by teshomem** [FabianGrammes/cluster_pipelines#8]
Hi,

I am not able to run sbatch-star-check.sh​ successfully.

I got 
------------------------------------------------
Using ID as id variables
Using ID as id variables
Using ID as id variables
Using ID as id variables
Error in list2env(members, envir = e) :
  names(x) must be a character vector of the same length as x
Calls: plot.all ... ggplot.data.frame -> structure -> scales_list -> ggproto -> list2env
Execution halted

/mnt/SeqData3/Anadromy/160203_7001448.B.Project_Sandve-RNAlibs2-2015-12-02/processed_data/data5/star/STAR_Log.Rout

Did you see this before?

Cheers!

**Comment by FabianGrammes** [comment]
Conflicting version of `reshape`

**Comment by timknut** [comment]
To what extent is reshape used? 
Can we switch to reshape2?

I can do it if you point me to the R-script @FabianGrammes .

**Comment by FabianGrammes** [comment]
`reshape` is just used for melting data.frames script: `helper_scripts/STAR_Log.R` lines 67-70. Knock yourself out :)

P.S also in `helper_scripts/HTseq_plot.R` line 52

**Comment by teshomem** [comment]
thanks :-)

**Comment by timknut** [comment]
Added to starlogs.R 
```{r}
library reshape2
..
..
plot.all <- function(x){
    d1 = reshape2::melt(x[2:3,])
    d2 = reshape2::melt(x[c(6:8,14,15),])
    d3 = reshape2::melt(x[c(21,23),])
    d4 = reshape2::melt(x[c(26,27),])
```
and 
```{r}
data <- HTSeq.logs()
write.table(data, file = "../mapp_summary/HTSeq_Count_Stats.txt", sep="\t", col.names=T, row.names=T, quote=F)
datM <- reshape2::melt(data)
```

Starlogs.R works if I `mkdir  ../mapp_summary` 
Can not test the HTSseq script.
